application: sf-trees
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  secure: always
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  secure: always
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: handlers/main.py
  